// <auto-generated />
using System;
using Healthcare.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Healthcare.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260404143210_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Healthcare.Core.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("BedNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobilityStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 58,
                            BedNumber = "12",
                            Department = "العناية المركزة",
                            FullName = "سعد عطية",
                            MobilityStatus = "غير قادر على الحركة"
                        },
                        new
                        {
                            Id = 2,
                            Age = 45,
                            BedNumber = "8",
                            Department = "العناية المركزة",
                            FullName = "محمد علي",
                            MobilityStatus = "غير قادر على الحركة"
                        },
                        new
                        {
                            Id = 3,
                            Age = 62,
                            BedNumber = "15",
                            Department = "العناية المركزة",
                            FullName = "فاطمة أحمد",
                            MobilityStatus = "غير قادر على الحركة"
                        });
                });

            modelBuilder.Entity("Healthcare.Core.Entities.PositionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ChangedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsMissed")
                        .HasColumnType("bit");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("TargetPosition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("PatientId");

                    b.ToTable("PositionLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChangedAt = new DateTime(2026, 4, 4, 13, 2, 6, 982, DateTimeKind.Utc).AddTicks(418),
                            ChangedByUserId = 1,
                            IsMissed = false,
                            PatientId = 1,
                            TargetPosition = "على الظهر"
                        },
                        new
                        {
                            Id = 2,
                            ChangedAt = new DateTime(2026, 4, 4, 13, 57, 6, 982, DateTimeKind.Utc).AddTicks(424),
                            ChangedByUserId = 1,
                            IsMissed = false,
                            PatientId = 2,
                            TargetPosition = "الجانب الأيمن"
                        },
                        new
                        {
                            Id = 3,
                            ChangedAt = new DateTime(2026, 4, 4, 10, 2, 6, 982, DateTimeKind.Utc).AddTicks(428),
                            ChangedByUserId = 1,
                            IsMissed = false,
                            PatientId = 3,
                            TargetPosition = "الجانب الأيسر"
                        });
                });

            modelBuilder.Entity("Healthcare.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Role = "Nurse",
                            Username = "hamid"
                        });
                });

            modelBuilder.Entity("Healthcare.Core.Entities.PositionLog", b =>
                {
                    b.HasOne("Healthcare.Core.Entities.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Healthcare.Core.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("Patient");
                });
#pragma warning restore 612, 618
        }
    }
}
